services:
    db1:
        image: postgres:12.1
        container_name: db1
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        command:
            - "postgres"
            - "-c"
            - "datestyle=dmy"

    db2:
        image: postgres:12.2
        container_name: db2
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        command:
            - "postgres"
            - "-c"
            - "datestyle=dmy"

    db3:
        image: postgres:12.3
        container_name: db3
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        command:
            - "postgres"
            - "-c"
            - "datestyle=dmy"
    redis:
        image: redis:latest
        container_name: redis1
        ports:
            - "6379:6379"
        env_file:
            - .env
    redis2:
        image: redis:7.4.0-alpine3.20
        container_name: redis2
        ports:
            - "6380:6379"
